# 1. Builder stage
FROM python:3.12-slim as builder
WORKDIR /app

# System dependencies for PostgreSQL and netcat (for entrypoint wait)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python packages (no compilation needed!)
COPY requirements.txt .
RUN pip wheel --no-cache-dir --wheel-dir /app/wheels -r requirements.txt

# 2. Production stage
FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

RUN addgroup --system --gid 1001 appgroup && \
    adduser --system --uid 1001 --ingroup appgroup appuser

COPY --from=builder /app/wheels wheels/
RUN pip install --no-cache-dir wheels/* && rm -rf wheels/
COPY --chown=appuser:appgroup . .

RUN chmod +x /app/IE221/entrypoint.sh
USER appuser
# Documentation
EXPOSE 8000

# Healthcheck, TODO list
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/').read()" || exit 1

ENTRYPOINT ["/app/IE221/entrypoint.sh"]