# Generated by Django 4.2.26 on 2025-11-06 12:16

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('gender', django_enum.fields.EnumCharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=256)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', django_enum.fields.EnumCharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'users',
            },
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(check=models.Q(('gender__in', ['MALE', 'FEMALE', 'OTHER'])), name='users_UserAccount_gender_Gender'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['ADMIN', 'USER'])), name='users_UserAccount_role_Role'),
        ),
    ]
