# Generated by Django 5.2.6 on 2025-09-28 16:08

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=django_enum.fields.EnumCharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=django_enum.fields.EnumCharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
<<<<<<< HEAD
            constraint=models.CheckConstraint(check=models.Q(('gender__in', ['MALE', 'FEMALE', 'OTHER'])), name='users_UserAccount_gender_Gender'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['ADMIN', 'USER'])), name='users_UserAccount_role_Role'),
=======
            constraint=models.CheckConstraint(check=models.Q(gender__in=['MALE', 'FEMALE', 'OTHER']), name='users_UserAccount_gender_Gender'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(check=models.Q(role__in=['ADMIN', 'USER']), name='users_UserAccount_role_Role'),
>>>>>>> 8a39f94 (feature: API Get current user's personal information)
        ),
    ]
