# Generated by Django 5.2.6 on 2025-10-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
