# Generated by Django 4.2.24 on 2025-10-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_useraccount_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
