# Generated by Django 5.2.6 on 2025-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.TextField(db_column='slug'),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slug_name',
        ),
    ]
