# Generated by Django 5.2.6 on 2025-10-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_slug_rename_slug_product_slug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
