# Generated by Django 4.2.26 on 2025-11-19 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_image_urls_productimage'),
        ('product', '0003_refactor_image_data_to_image_url'),
    ]

    operations = [
    ]
