# Generated by Django 5.2.8 on 2025-11-22 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_recommendation_interact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interact',
            index=models.Index(fields=['product', 'created_at'], name='interact_product_e02f58_idx'),
        ),
        migrations.AddIndex(
            model_name='interact',
            index=models.Index(fields=['user', 'created_at', 'product'], name='interact_user_id_957e90_idx'),
        ),
    ]
